- hosts: localhost
  become: true
  tasks:
  - name: Install htop
    apt: name=htop

  - name: Install vim
    apt: name=vim

  - name: Install wireshark
    apt: name=wireshark

  - name: Install deluge
    apt: name=deluge

  - name: Install nmap
    apt: name=nmap

  - name: Install irssi
    apt:  name=irssi

  - name: Install ssldump
    apt: name=ssldump
  
  - name: Install tmux
    apt: name=tmux

  - name: Install Flatpak
    apt: name=flatpak

  - name: Install Flatpak-Apps
    community.general.flatpak:
      name:
        - org.signal.Signal
        - com.slack.Slack
        - org.eclipse.Java
        - io.freetubeapp.FreeTube
        - io.github.mimbrero.WhatsAppDesktop
        - md.obsidian.Obsidian   
  
  - name: virtual machine package-pattern
    apt:
      state: present
      install_recommends: false
      pkg:
        - virt-manager
        - ruby
        - ruby-dev
        - vagrant
        - libvirt-clients
        - libvirt-daemon-system
      update_cache: true

  ###docker install###

  - name: Docker dep
    apt:
      state: present
      install_recommends: false
      pkg:
        - bridge-utils
        - ca-certificates
        - curl
        - gnupg
      update_cache: true


  - name: get architecture
    shell: dpkg --print-architecture
    register: deb_architecture

  - name: get gpg key
    get_url:
      url: https://download.docker.com/linux/debian/gpg
      dest: /etc/apt/keyrings/docker.asc
      mode: 0644
      force: true
    tags: install_docker

  - name: add docker apt repository
    apt_repository:
       repo: "deb [arch={{ deb_architecture.stdout }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
       state: present
       update_cache: yes
       filename: docker
    tags: install_docker

  - name: install docker and related components
    apt:
      name:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-buildx-plugin
        - docker-compose-plugin
      state: latest
      update_cache: true
    tags: install_docker
    
  - name: restart Docker 
    systemd:
      name: docker
      state: restarted 
      masked: no
    tags: install_docker

  - name: adduser to docker
    user:
      name: xtify
      groups: docker
      append: yes

  - name: adduser to libvirtd
    user:
      name: xtify
      groups: libvirt
      append: yes

  - name: restart servicies
    service:  
      name: "{{ item }}"
      state: restarted
      enabled: yes
<<<<<<< HEAD
    with_item:
=======
    loop:
>>>>>>> deb_ansible_dev
      - docker
      - libvirt
    

        
